AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - Gemfile
    - Rakefile

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 150
  Exclude:
    - "config/**/*"
    - "db/**/*"

Metrics/AbcSize:
  Max: 40
  Exclude:
    - "spec/**/*"
    - "db/migrate/*"

Metrics/BlockLength:
  Max: 100
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 300
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 40
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 12

Naming/PredicateName:
  Enabled: false
